package models

import (
	"time"

	"gorm.io/datatypes"
)

// GroupTask maps `group_tasks`.
type GroupTask struct {
	ID              uint64         `gorm:"primaryKey"`
	GroupID         *uint64        `gorm:"column:group_id"`
	SourceType      *string        `gorm:"column:source_type"`
	SourceID        *uint64        `gorm:"column:source_id"`
	EventType       *string        `gorm:"column:event_type"`
	TeamType        *string        `gorm:"column:team_type"`
	Title           *string        `gorm:"column:title"`
	Description     *string        `gorm:"column:description"`
	ScheduledAt     *time.Time     `gorm:"column:scheduled_at"`
	AssignedUserID  *uint64        `gorm:"column:assigned_user_id"`
	AssignedRole    *string        `gorm:"column:assigned_role"`
	IsAutoGenerated bool           `gorm:"column:is_auto_generated"`
	Status          *string        `gorm:"column:status"`
	CompletedAt     *time.Time     `gorm:"column:completed_at"`
	CompletionPhoto *string        `gorm:"column:completion_photo"`
	Checklist       datatypes.JSON `gorm:"column:checklist"`
	CompletionNote  *string        `gorm:"column:completion_note"`
	GenerationKey   *string        `gorm:"column:generation_key"`
	Meta            datatypes.JSON `gorm:"column:meta"`
	CreatedAt       time.Time      `gorm:"column:created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at"`

	Group        *Group `gorm:"foreignKey:GroupID"`
	AssignedUser *User  `gorm:"foreignKey:AssignedUserID"`
}

func (GroupTask) TableName() string { return "group_tasks" }

// IsScheduledInFuture mirrors GroupTask::isScheduledInFuture.
func (t *GroupTask) IsScheduledInFuture() bool {
	return t.ScheduledAt != nil && t.ScheduledAt.After(time.Now())
}

// ChecklistItem is one entry of GroupTask.Checklist.
type ChecklistItem struct {
	Title string `json:"title,omitempty"`
	Done  bool   `json:"done"`
}
